### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by synergy6** [saintsystems/dynamics-sdk-php#6]
Details

Type: Error
Message: Call to undefined function SaintSystems\OData\class_uses_recursive()
File: C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\app\dynamics\src\OData\Entity.php
Line: 225
Trace

#0 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\app\dynamics\src\OData\Entity.php(213): SaintSystems\OData\Entity::bootTraits()
#1 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\app\dynamics\src\OData\Entity.php(200): SaintSystems\OData\Entity::boot()
#2 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\app\dynamics\src\OData\Entity.php(179): SaintSystems\OData\Entity->bootIfNotBooted()
#3 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\app\dynamics\src\Dynamics\Http\DynamicsResponse.php(146): SaintSystems\OData\Entity->__construct(Array)
#4 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\app\dynamics\src\Dynamics\Http\DynamicsRequest.php(284): Microsoft\Dynamics\Http\DynamicsResponse->getResponseAsObject('Microsoft\\Dynam...')
#5 C:\WampDeveloper\Websites\ptl-link.dezrez.com\webroot\app\src\Controllers\_Controller_oAuth2_DezrezCRM.php(173): Microsoft\Dynamics\Http\DynamicsRequest->execute()

**Comment by anderly** [comment]
Can you share the usage when you encountered this error?

**Comment by oktron** [comment]
You are using a function from Laravel see [Helpers](https://laravel.com/docs/6.x/helpers#method-class-uses-recursive).

Maybe [class_uses()](https://www.php.net/manual/en/function.class-uses.php) can help
